# Stack file for the Conjure program generation library.
#
# Copyright (C) 2021-2024 Rudy Matela
# Distributed under the 3-Clause BSD licence (see the file LICENSE).

resolver: lts-19.19 # or ghc-9.0.2

packages:
- .

extra-deps:
- leancheck-1.0.2
- speculate-0.4.18
- express-1.0.16
