# Stack file for the Conjure program generation library.
#
# Copyright (C) 2021 Rudy Matela
# Distributed under the 3-Clause BSD licence (see the file LICENSE).

resolver: lts-17.9 # or ghc-8.10.4

packages:
- .

extra-deps:
- leancheck-0.9.10
- speculate-0.4.14
- express-1.0.8
