# Stack file for the Conjure program generation library.
#
# Copyright (C) 2021 Rudy Matela
# Distributed under the 3-Clause BSD licence (see the file LICENSE).

resolver: lts-18.14 # or ghc-8.10.7

packages:
- .

extra-deps:
- leancheck-0.9.10
- speculate-0.4.14
- express-1.0.8
