# Stack file for the Conjure program generation library.
#
# Copyright (C) 2021 Rudy Matela
# Distributed under the 3-Clause BSD licence (see the file LICENSE).

resolver: lts-17.9 # or ghc-8.10.4

packages:
- .

extra-deps:
- leancheck-0.9.6
- speculate-0.4.6
- express-0.1.10
