# Stack file for the Conjure program generation library.
#
# Copyright (C) 2021 Rudy Matela
# Distributed under the 3-Clause BSD licence (see the file LICENSE).

resolver: lts-15.6 # or ghc-8.8.3

packages:
- .

extra-deps:
- leancheck-0.9.4
- speculate-0.4.6
- express-0.1.6
